name: Check on Pull Request

on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/**/*.kt'

jobs:
  test-lint:
    uses: ./.github/workflows/test-lint.yml
  test-small:
    uses: ./.github/workflows/test-small.yml
