name: Lint Check

on:
  workflow_call:

jobs:
  test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Lint check
        run: mvn -B spotless:check
